### ISSUE TITLE
test case, precision matrix

### ISSUE THREAD

**Issue by beef-broccoli** [leeyang/ResPRE#1]
Hello,

I was running ResPRE on the given test case, and saved the calculated precision matrix (21*L, 21*L). This is the precision matrix printed out:

[[14.20261936  0.          0.         ...  0.          0.         0.        ]
 [ 0.         14.20261936  0.         ...  0.          0.          0.        ]
 [ 0.          0.         14.20261936 ...  0.          0.          0.        ]
 ...
 [ 0.          0.          0.         ... 14.20261936  0.         0.        ]
 [ 0.          0.          0.          ...  0.         14.20261936 0.        ]
 [ 0.          0.          0.         ...  0.          0.        14.20261936]]

It looks like this is just an identity matrix. I was wondering whether this is the correct output (persumably not)? And what might be the issue? I have not modified the code, other than adding one line to save the returned precision matrix. 

Thanks,

**Comment by leeyang** [comment]
Hi,

How do you save the precision matrix? Here the precision matrix should be at 
`https://github.com/leeyang/ResPRE/blob/f917e55c7a5e121b36e533bcde0250133847a357/respre.py#L88`
The shape of precision matrix should be [441,L,L]. Is it possible that you only save pre[0]?

Thanks,

**Comment by beef-broccoli** [comment]
Thanks for the response. I saved the precision matrix before the reshaping so it's (21L,21L). I think the weight wasn't calculated correctly which might be the problem. I used the given weight file directly and it seems to be working now.
